### ISSUE TITLE
احتمال ديسكربشن مختلف زي "Roadmap to becoming a blockchain developer" احسن

### ISSUE THREAD

**Issue by BlankAlmasry** [ArabsInBlockchain/BC-Roadmap#2]
الديسكربشن نوعا ما قرأته غريبة
Simple Roadmap blockchain enthusiasts to learn about blockchain
الجرامر غريب شوية

**Comment by EmanHerawy** [comment]
معذرة ما انتبهت وانا بعدل فحذفت
 for
 ، شكرا ليك
